In [107]:
import numpy as np
import math
from scipy.linalg import expm

In [77]:
pauli = np.array([[0, -1j],[1j, 0]])

In [78]:
eigvalues, eigvectors = np.linalg.eig(pauli)

In [79]:
eigvalues, eigvectors

(array([ 1.+0.j, -1.+0.j]),
 array([[-0.00000000-0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.00000000-0.70710678j]]))

In [80]:
np.matmul(pauli, eigvectors[0])

array([ 0.00000000-0.70710678j,  0.70710678+0.j        ])

In [81]:
np.matmul(pauli, eigvectors[1])

array([-0.70710678+0.j        ,  0.00000000+0.70710678j])

In [82]:
reshaper = lambda v: np.expand_dims(v, axis=1)
eigvectors = np.array([reshaper(v) for v in eigvectors])

In [83]:
eigvalues, eigvectors

(array([ 1.+0.j, -1.+0.j]), array([[[-0.00000000-0.70710678j],
         [ 0.70710678+0.j        ]],
 
        [[ 0.70710678+0.j        ],
         [ 0.00000000-0.70710678j]]]))

In [85]:
result = np.zeros((2, 2))
for i in range(eigvectors.shape[0]):
    result = np.add(result, eigvalues[i]*np.matmul(eigvectors[i], np.conj(eigvectors[i].T)))
print(result)

[[ -4.44089210e-16+0.j   0.00000000e+00-1.j]
 [  0.00000000e+00+1.j  -1.66533454e-16+0.j]]


In [89]:
B = np.array([[1/np.sqrt(2), 1j/np.sqrt(2)], [1/np.sqrt(2), -1j/np.sqrt(2)]])

In [91]:
Bdagger = np.matrix(B).getH()

In [95]:
np.matmul(np.matmul(Bdagger, pauli), B)

matrix([[ 0. -2.23711432e-17j, -1. +0.00000000e+00j],
        [-1. +0.00000000e+00j,  0. +2.23711432e-17j]])

In [98]:
np.matmul(np.matmul(B, pauli), B.T)

array([[ 0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+0.j]])

In [99]:
np.matmul(np.matmul(np.conj(B), pauli), B.T)

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [116]:
sigmax = np.array([[0, 1],[1, 0]])

In [117]:
eigvalx, eigvecx = np.linalg.eig(sigmax)

In [118]:
eigvalx, eigvecx

(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [137]:
sigmay = np.array([[0, -1j], [1j, 0]])

In [138]:
def psi(B, t, sigma, psi_0):
    u_t = expm(1j*B*sigma*t)
    psi_t = np.matmul(u_t, psi_0)
    return psi_t

In [139]:
psi_t = psi(1, 1, sigmay, eigvecx[:, 0].reshape((2, 1)))

In [140]:
psi_t_dag = np.conj(psi_t.T)

In [141]:
psi_t, psi_t_dag

(array([[ 0.97706126+0.j],
        [-0.21295842+0.j]]), array([[ 0.97706126-0.j, -0.21295842-0.j]]))

In [143]:
np.matmul(np.matmul(psi_t_dag, sigmax), psi_t)[0][0]

(-0.41614683654714218+0j)

In [146]:
psis = np.array((1, 10))
for t in range(10):
    psi_t = psi(1, t, sigmay, eigvecx[:, 0].reshape((2, 1)))
    psis[t] = np.matmul(np.matmul(psi_t_dag, sigmax), psi_t)[0][0]

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:4: ComplexWarning: Casting complex values to real discards the imaginary part
  after removing the cwd from sys.path.


IndexError: index 2 is out of bounds for axis 0 with size 2